import API from './authApi'

export const createTest = (data) => API.post('/api/tests', data)
export const getMyTests = () => API.get('/api/tests/my')
export const getTestById = (id) => API.get(`/api/tests/${id}`)
export const updateTest = (id, data) => API.patch(`/api/tests/${id}`, data)
export const addQuestion = (id, data) => API.post(`/api/tests/${id}/questions`, data)
export const addBulkQuestions = (id, data) => API.post(`/api/tests/${id}/questions/bulk`, data)
export const deleteQuestion = (id, qId) => API.delete(`/api/tests/${id}/questions/${qId}`)
export const publishTest = (id) => API.patch(`/api/tests/${id}/publish`)
export const closeTest = (id) => API.patch(`/api/tests/${id}/close`)
export const deleteTest = (id) => API.delete(`/api/tests/${id}`)
export const getTestAnalytics = (id) => API.get(`/api/tests/${id}/analytics`)
export const generateQuestionsAI = (data) => API.post('/api/tests/ai-generate', data)
export const getAvailableTests = () => API.get('/api/tests/available')
export const startTest = (id) => API.post(`/api/tests/${id}/start`)
export const submitTest = (id, data) => API.post(`/api/tests/${id}/submit`, data)
export const getTestResult = (id) => API.get(`/api/tests/${id}/result`)
export const getAllTestsAdmin = () => API.get('/api/tests')
export const getAnalyticsOverview = () => API.get('/api/tests/analytics/overview')
export const getTestLeaderboard = (id) => API.get(`/api/tests/${id}/leaderboard`)